import React from "react";
import parse from "html-react-parser";
import "./InfoduceWeb.scss";
const introduce = `
<div class="work">
   <div class="work-home">
      <span>Trang chủ</span> 
      <svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="ArrowForwardIcon">
         <path d="m12 4-1.41 1.41L16.17 11H4v2h12.17l-5.58 5.59L12 20l8-8z"></path>
      </svg>
      Hướng dẫn mua hàng trên C&D
   </div>
   <div class="work-title">QUY CHẾ HOẠT ĐỘNG CỦA Website dịch vụ thiết kế sửa chữa lắp đặt</div>
   <div class="work-body">
      <div class="work-text">C&D là Sàn giao dịch thương mại điện tử thuộc website cung cấp dịch vụ thương mại điện tử mang thương hiệu nổi tiếng, do Viện quản trị Logistics Toàn cầu (GLI) vận hành chuyên về nông sản, thực phẩm, đồ uống, quà tặng, vật phẩm đồng thương hiệu ,… cho phép các tổ chức kinh doanh bán hàng trên Sàn giao dịch thương mại điện tử C&D cũng như cung cấp các dịch vụ liên quan đến việc bán hàng, xử lý đơn hàng, vận chuyển hàng đến cho Khách Hàng.</div>
      <div class="work-text" style="margin-bottom: 40px;">Sứ mệnh mà Sàn giao dịch thương mại điện tử C&D hướng tới là trở thành kênh thương mại điện tử tin cậy, là cầu nối thương mại giữa Nhà Bán Hàng và Khách Hàng, giữa doanh nghiệp với doanh nghiệp.</div>
      <div class="work-bold">I. NGUYÊN TẮC CHUNG</div>
      <div class="work-text" style="margin-bottom: 40px;">1. Sàn giao dịch thương mại điện tử (TMĐT) C&D do Tổng công ty C&D Việt Nam – CTCP và Viện quản trị Logistics Toàn cầu - GLI (sau đây gọi là “Công ty”) cùng thiết lập, quản lý và vận hành. Thành viên trên Website dịch vụ thiết kế sửa chữa lắp đặt là các thương nhân có hoạt động thương mại hợp pháp, được Website dịch vụ thiết kế sửa chữa lắp đặt chính thức công nhận và được phép sử dụng các dịch vụ do Website dịch vụ thiết kế sửa chữa lắp đặt và các bên liên quan cung cấp. </div>
      <div class="work-text" style="margin-bottom: 40px;">2. Quy chế hoạt động của Website dịch vụ thiết kế sửa chữa lắp đặt ban hành các quy định bắt buộc áp dụng đối với các thương nhân đăng ký sử dụng và tạo lập gian hàng trên Website dịch vụ thiết kế sửa chữa lắp đặt để giới thiệu, buôn bán hàng hóa và cung ứng dịch vụ tới Khách Hàng (sau đây gọi là “Nhà bán hàng”).</div>
      <div class="work-text" style="margin-bottom: 40px;">3. Bằng việc tham gia giao dịch trên Website dịch vụ thiết kế sửa chữa lắp đặt, Nhà bán hàng và Khách Hàng được xem là đã tìm hiểu quyền và nghĩa vụ của mình và đồng ý bị ràng buộc bởi Quy chế hoạt động của Website dịch vụ thiết kế sửa chữa lắp đặt (sau đây gọi là "Quy Chế") đang có hiệu lực vào thời điểm Nhà bán hàng và Khách Hàng thực hiện giao dịch.</div>
      <div class="work-text" style="margin-bottom: 40px;">4. Hoạt động mua bán hàng hóa và cung ứng dịch vụ qua Website dịch vụ thiết kế sửa chữa lắp đặt phải được thực hiện hợp pháp, công khai, minh bạch, đảm bảo quyền lợi của người tiêu dùng. Trong mọi trường hợp, Nhà bán hàng sẽ hoàn toàn chịu trách nhiệm trước Khách Hàng đối với mọi vấn đề liên quan đến sản phẩm và dịch vụ do Nhà bán hàng cung cấp trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
      <div class="work-text" style="margin-bottom: 40px;">5. Nhà bán hàng tham gia giao dịch trên Website dịch vụ thiết kế sửa chữa lắp đặt được tự do thỏa thuận với Khách Hàng trên cơ sở tôn trọng quyền và lợi ích hợp pháp của các bên tham gia hoạt động mua bán hàng hóa thông qua hợp đồng và không trái với quy định của pháp luật.</div>
      <div class="work-text" style="margin-bottom: 40px;">6. Sản phẩm tham gia giao dịch trên Website dịch vụ thiết kế sửa chữa lắp đặt phải hợp pháp, không thuộc danh mục các hàng hóa cấm kinh doanh, cấm quảng cáo theo quy định của pháp luật và phải đáp ứng đầy đủ các quy định của pháp luật về điều kiện kinh doanh.</div>
      <div class="work-text" style="margin-bottom: 40px;">7. Tất cả các nội dung trong Quy chế này phải tuân thủ theo hệ thống pháp luật hiện hành của Việt Nam. Nhà bán hàng khi tham gia vào Website dịch vụ thiết kế sửa chữa lắp đặt phải tự tìm hiểu trách nhiệm pháp lý của mình đối với luật pháp hiện hành của Việt Nam và cam kết tuân thủ quy định pháp luật và nội dung Quy chế hoạt động của Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
      <div class="work-bold">II. QUY ĐỊNH CHUNG</div>
      <div class="work-text"><span>1. Tên miền của Website dịch vụ thiết kế sửa chữa lắp đặt:</span> http://C&D.smiletech.vn/</div>
      <div class="work-text" style="margin-bottom: 40px;">Ngoài địa chỉ trên, Website dịch vụ thiết kế sửa chữa lắp đặt không có bất kỳ địa chỉ giao dịch nào khác. </div>
      <div class="work-text" style="margin-bottom: 40px;"><span> 2. Website dịch vụ thiết kế sửa chữa lắp đặt:</span> là nơi giao thương giữa người mua và người bán, đồng thời giúp quá trình mua bán hàng hóa qua mạng được thực hiện một cách nhanh gọn, trọn vẹn bằng việc tích hợp tính năng thanh toán trực tuyến. </div>
      <div class="work-text" style="margin-bottom: 40px;"><span>3. Sản phẩm giao dịch trên Website dịch vụ thiết kế sửa chữa lắp đặt (sau đây gọi là “Sản phẩm”):</span> là hàng hóa bao gồm nhưng không giới hạn hàng nông sản, thực phẩm, đồ uống, quà tặng, vật phẩm đồng thương hiệu  và các dịch vụ liên quan đến hàng hóa được giới thiệu và cung cấp trên Website dịch vụ thiết kế sửa chữa lắp đặt. </div>
      <div class="work-text" style="margin-bottom: 40px;"><span>4. Nhà Bán Hàng:</span> là các tổ chức/nhà cung cấp/đối tác có nhu cầu giới thiệu, bán Sản phẩm trên Website dịch vụ thiết kế sửa chữa lắp đặt và đã ký hợp đồng với  để sử dụng các dịch vụ của Website dịch vụ thiết kế sửa chữa lắp đặt bao gồm nhưng không giới hạn: tạo lập gian hàng, giới thiệu về Sản phẩm, giới thiệu về tổ chức, đăng bán Sản phẩm, thực hiện cung cấp dịch vụ cho Khách Hàng. </div>
      <div class="work-text" style="margin-bottom: 40px;"><span> 5. Khách Hàng:</span> tham gia giao dịch trên Website dịch vụ thiết kế sửa chữa lắp đặt: là (i) mọi cá nhân có đầy đủ năng lực hành vi dân sự và có tài sản để thực hiện giao dịch mua Sản Phẩm trên Website dịch vụ thiết kế sửa chữa lắp đặt; và (ii) mọi tổ chức được thành lập và hoạt động hợp pháp theo quy định của pháp luật Việt Nam (sau đây gọi là "Khách Hàng"). Khách Hàng có quyền đăng ký tài khoản hoặc không cần đăng ký tài khoản để sử dụng dịch vụ của Website dịch vụ thiết kế sửa chữa lắp đặt. Khách Hàng có quyền mua Sản phẩm theo đúng giá và quy chuẩn được cam kết bởi Nhà Bán Hàng và được công bố trên Website dịch vụ thiết kế sửa chữa lắp đặt. </div>
      <div class="work-bold">III. QUY TRÌNH GIAO DỊCH</div>
      <div class="work-bold" style="margin-bottom: 40px;">1. Quy trình dành cho Khách Hàng: </div>
      <div class="work-text" style="margin-bottom: 40px;">Khi có nhu cầu mua Sản phẩm, Khách Hàng nên thực hiện theo các bước sau đây:</div>
      <div class="work-text" style="margin-bottom: 40px;"><span> Bước 1:</span> Khách hàng tìm kiếm, tham khảo thông tin Sản phẩm và Nhà bán hàng ở khu vực mà Khách Hàng đang quan tâm bằng cách điền thông tin vào thanh <span>“Tìm kiếm”</span> hoặc xem tại <span>“Sản phẩm”</span> trên giao diện chính của Website dịch vụ thiết kế sửa chữa lắp đặt. </div>
      <div class="work-text" style="margin-bottom: 40px;"><span>Bước 2:</span> Xem thông tin chi tiết về Sản phẩm của Nhà bán hàng, tham khảo thông tin giá và chính sách, điều khoản điều kiện mua Sản phẩm của Nhà bán hàng mà Khách hàng đang có nhu cầu mua.</div>
      <div class="work-text" style="margin-bottom: 40px;"><span> Bước 3:</span> Sau khi tham khảo thông tin và so sánh giá cả, chất lượng Sản phẩm, Khách Hàng đặt Sản phẩm muốn mua bằng cách chọn nút<span> “Thêm vào giỏ hàng”</span> rồi nhấn nút <span>“Xem giỏ hàng của tôi”</span> và chọn <span>“Tiến hành thanh toán”</span> để chuyển sang bước thanh toán. </div>
      <div class="work-text" style="margin-bottom: 40px;"><span>Bước 4:</span> Nhập thông tin của Khách Hàng và địa chỉ nhận hàng và chọn<span> “Tiếp tục đến phương thức thanh toán”</span> sau đó nhập các thông tin theo quy định và chọn <span>“Hoàn tất đơn hàng”</span> để gửi đơn hàng đến Nhà bán hàng. Đơn hàng của Khách Hàng sẽ được chuyển đến Nhà bán hàng. Nhà bán hàng xác nhận đơn hàng và thực hiện chuẩn bị đơn hàng. Đơn vị vận chuyển của Website dịch vụ thiết kế sửa chữa lắp đặt tiến hành đến lấy hàng và giao hàng cho Khách Hàng.</div>
      <div class="work-bold">2. Chính sách giao nhận, vận chuyển Sản phẩm</div>
      <div class="work-text" style="margin-bottom: 40px;">2.1. Sau khi nhận được đơn hàng từ Khách Hàng, Website dịch vụ thiết kế sửa chữa lắp đặt sẽ chuyển thông tin đơn hàng đến Nhà Bán Hàng và xác nhận hình thức giao dịch.</div>
      <div class="work-text" style="margin-bottom: 40px;">2.2. Thông tin về đơn hàng đã xác nhận sẽ được tự động chuyển tới Đơn vị vận chuyển của Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
      <div class="work-text" style="margin-bottom: 40px;">2.3. Nhân viên giao hàng sẽ tới địa chỉ của Nhà Bán Hàng lấy Sản phẩm và vận chuyển Sản phẩm đó tới địa chỉ nhận hàng của Khách Hàng.</div>
      <div class="work-text" style="margin-bottom: 40px;">2.4. Phí dịch vụ vận chuyển sẽ được tính theo biểu phí của từng Đơn vị vận chuyển. Phí dịch vụ vận chuyển sẽ được hiển thị chi tiết trong từng đơn hàng của Khách Hàng.</div>
      <div class="work-text" style="margin-bottom: 40px;">2.5. Thời gian giao hàng:</div>
      <div class="work-text" style="margin-bottom: 40px;">- Thời gian giao hàng được bắt đầu tính từ lúc Khách Hàng thanh toán thành công đến khi Đơn vị vận chuyển liên hệ lần đầu tiên với Khách Hàng để giao hàng.</div>
      <div class="work-text" style="margin-bottom: 40px;">- Thời gian giao hàng cụ thể phụ thuộc vào khoảng cách địa lý giữa Khách Hàng và Nhà Bán Hàng. Tuy nhiên, Website dịch vụ thiết kế sửa chữa lắp đặt ước tính thời gian giao hàng như sau:</div>
      <div class="work-text">Vận chuyển thông qua Ahamove trong phạm vi Nội thành Hà Nội/TP Hồ Chí Minh: 02 giờ</div>
      <div class="work-text" style="margin-bottom: 40px;">Vận chuyển thông qua các đơn vị chuyển phát bưu điện ở ngoại thành Hà Nội/ TP Hồ Chí Minh: 01-02 ngày (không kể Chủ nhật, ngày Lễ). </div>
      <div class="work-text" style="margin-bottom: 40px;"><span>Lưu ý:</span> Một số đơn hàng có thể sẽ vận chuyển lâu hơn do Nhà Bán Hàng hẹn lại lịch lấy Sản phẩm lâu hơn dự kiến hoặc Khách Hàng </div>
      <div class="work-bold">3. Chính sách bảo hành </div>
      <div class="work-text" style="margin-bottom: 40px;">3.1. Đối với các Sản phẩm có bảo hành theo quy định của pháp luật, Nhà Bán Hàng cung cấp cho Khách hàng đầy đủ và chính xác thông tin và cam kết về điều kiện, thời hạn, địa điểm, thủ tục bảo hành trong mục mô tả Sản phẩm trên gian hàng của Nhà Bán Hàng. </div>
      <div class="work-text" style="margin-bottom: 40px;">3.2. Đối với các mặt hàng trái cây, nông sản: Không có chính sách bảo hành như các mặt hàng khác, trừ trường hợp Nhà Bán Hàng có chính sách riêng được cập nhật cụ thể trong mục mô tả Sản phẩm trên gian hàng của Nhà Bán Hàng.</div>
      <div class="work-text" style="margin-bottom: 40px;">3.3. Khi tiến hành giao dịch, Khách Hàng cần tìm hiểu về các chính sách bảo hành Sản phẩm của Nhà Bán Hàng trong mục mô tả Sản phẩm hoặc sẽ được ghi trong phiếu/tem/ mã bảo hành kèm theo Sản phẩm. Nếu Khách Hàng có nhu cầu bảo hành Sản phẩm, vui lòng liên hệ trực tiếp với Nhà Bán Hàng hoặc các Trung tâm bảo hành sản phẩm chính hãng được ghi trên phiếu bảo hành đính kèm Sản phẩm.</div>
      <div class="work-text" style="margin-bottom: 40px;">3.4. Nhà Bán Hàng và các Trung tâm bảo hành sản phẩm của mình có trách nhiệm tiếp nhận bảo hành Sản phẩm cho Khách Hàng như trong cam kết về bảo hành Sản phẩm. Mọi thông tin của Nhà Bán Hàng phải được ghi trên hóa đơn điện tử xuất cho Khách Hàng hoặc phiếu biên nhận giao hàng/hóa đơn được đính kèm Sản phẩm.</div>
      <div class="work-bold">4. Chính sách đổi - trả Sản phẩm và hoàn tiền </div>
      <div class="work-text" style="margin-bottom: 40px;">4.1.Việc thực hiện đổi - trả Sản phẩm và hoàn tiền sẽ được thực hiện theo quy định Chính sách và quy trình xử lý đổi, trả Sản phẩm và hoàn tiền của Website dịch vụ thiết kế sửa chữa lắp đặt. Vui lòng xem chi tiết tại đây.</div>
      <div class="work-text" style="margin-bottom: 40px;">4.2. Nhà Bán Hàng nghĩa vụ tuân theo các chính sách và quy trình xử lý đổi – trả Sản phẩm và hoàn tiền để đảm bảo quyền lợi của Khách Hàng.</div>
      <div class="work-text" style="margin-bottom: 40px;">4.3. Website dịch vụ thiết kế sửa chữa lắp đặt khuyến cáo Khách Hàng phải đọc kĩ thông tin về chính sách đổi - trả Sản phẩm đối với từng Sản phẩm trước khi đưa ra quyết định đặt mua Sản phẩm và tuân thủ các điều kiện và quy trình đổi – trả Sản phẩm. Website dịch vụ thiết kế sửa chữa lắp đặt sẽ hỗ trợ Khách Hàng trong khả năng cho phép về việc đổi - trả Sản phẩm.</div>
      <div class="work-bold">5. Quy trình giải quyết khiếu nại</div>
      <div class="work-text" style="margin-bottom: 40px;">5.1. Website dịch vụ thiết kế sửa chữa lắp đặt luôn có trách nhiệm tiếp nhận và xử lý khiếu nại của Khách Hàng liên quan đến các giao dịch tại Website dịch vụ thiết kế sửa chữa lắp đặt. Khi phát sinh các khiếu nại, tranh chấp, Website dịch vụ thiết kế sửa chữa lắp đặt đề cao giải pháp thương lượng, hòa giải giữa các bên nhằm duy trì mối quan hệ, sự tin cậy của Khách Hàng vào chất lượng dịch vụ của Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
      <div class="work-text" style="margin-bottom: 40px;">5.2. Quy trình khiếu nại thực hiện theo các bước sau:</div>
      <div class="work-text" style="margin-bottom: 40px;"><span> Bước 1:</span> Khách Hàng khiếu nại về Sản phẩm của Nhà Bán Hàng trên Website dịch vụ thiết kế sửa chữa lắp đặt thông qua 02 kênh thông tin sau:</div>
      <div class="work-text" style="margin-bottom: 40px;">- Kênh số 1: Bộ phận CSKH của Website dịch vụ thiết kế sửa chữa lắp đặt:</div>
      <div class="work-text">Gửi thư đến địa chỉ Email: C&D.smiletech.vn</div>
      <div class="work-text">
         Gọi điện đến Hotline: 1900 1033.
         <div class="work-text">Khách Hàng gửi khiếu nại tại địa chỉ:</div>
         <div class="work-text">Văn phòng miền Bắc: Địa chỉ FWW: Số 12 đường 5, KTT F361 đường An Dương, Phường Yên Phụ, Quận Tây Hồ, Hà Nội</div>
         <div class="work-text">Văn phòng miền Nam: Lầu 11, 39B Trường Sơn, phường 4, quận Tân Bình, Tp. Hồ Chí Minh.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Kênh số 2: Liên hệ trực tiếp với Nhà Bán Hàng thông qua các thông tin trên email Xác nhận thanh toán hàng thành công hoặc hoá đơn điện tử mà Nhà Bán Hàng đã xuất cho Khách Hàng hoặc phiếu biên nhận giao hàng/hóa đơn được đính kèm Sản phẩm.</div>
         <div class="work-text" style="margin-bottom: 40px;"><span> Bước 2:</span> Khi nhận được thông tin khiếu nại từ Khách Hàng, Bộ phận CSKH của Website dịch vụ thiết kế sửa chữa lắp đặt sẽ tiếp nhận, liên hệ làm rõ các yêu cầu của Khách hàng trong</div>
         <div class="work-text" style="margin-bottom: 40px;">(i) Đưa ra biện pháp xử lý, phương án cụ thể để giải quyết khiếu nại, tranh chấp của Khách Hàng trên cơ sở đạt được sự đồng thuận với Khách Hàng hoặc</div>
         <div class="work-text" style="margin-bottom: 40px;">(ii) Chuyển khiếu nại của Khách Hàng đến Nhà Bán Hàng để Nhà Bán Hàng trực tiếp giải quyết và báo cho Khách Hàng biết. Website dịch vụ thiết kế sửa chữa lắp đặt vẫn tiếp tục theo dõi quá trình giải quyết khiếu nại của Nhà Bán Hàng. Trong trường hợp Khách Hàng không đồng ý với phương án giải quyết khiếu nại của Nhà Bán Hàng, Khách Hàng có thể gửi lại yêu cầu, khiếu nại về Website dịch vụ thiết kế sửa chữa lắp đặt. Website dịch vụ thiết kế sửa chữa lắp đặt sẽ xem xét, trực tiếp giải quyết và quyết định phương án giải quyết yêu cầu, khiếu nại cuối cùng.</div>
         <div class="work-text" style="margin-bottom: 40px;">Trong trường hợp Khách Hàng liên hệ trực tiếp với Nhà Bán Hàng hoặc Nhà Bán Hàng nhận thông tin về khiếu nại từ Website dịch vụ thiết kế sửa chữa lắp đặt, Nhà Bán Hàng có trách nhiệm tiếp nhận; thu thập thông tin, chứng cứ từ các bên liên quan; đưa ra phán quyết và hướng khắc phục sau đó thống nhất phương án giải quyết khiếu nại với Khách Hàng và báo cho Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;"><span>Bước 3:</span> Nhà Bán Hàng và/hoặc Website dịch vụ thiết kế sửa chữa lắp đặt và Khách Hàng thực hiện các công việc đã thống nhất để giải quyết khiếu nại, sau đó xác nhận kết quả và tiến hành đóng khiếu nại.</div>
         <div class="work-bold">Lưu ý: </div>
         <div class="work-text" style="margin-bottom: 40px;">- Website dịch vụ thiết kế sửa chữa lắp đặt có thể yêu cầu Khách hàng và/hoặc Nhà Bán Hàng cung cấp các thông tin, bằng chứng liên quan đến giao dịch, Sản phẩm để xác minh, làm rõ vụ việc và đưa ra phương hướng xử lý, giải quyết phù hợp.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Trong trường hợp Website dịch vụ thiết kế sửa chữa lắp đặt đã nỗ lực giải quyết khiếu nại, tranh chấp nhưng vụ việc vượt quá khả năng và thẩm quyền của Website dịch vụ thiết kế sửa chữa lắp đặt, Website dịch vụ thiết kế sửa chữa lắp đặt sẽ yêu cầu Khách hàng đưa vụ việc ra cơ quan Nhà nước có thẩm quyền giải quyết theo quy định của pháp luật.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Trong trường hợp giao dịch phát sinh khiếu nại, tranh chấp mà được xác định lỗi thuộc về Nhà Bán Hàng, tuy vào mức độ vi phạm của Nhà Bán Hàng, Website dịch vụ thiết kế sửa chữa lắp đặt có quyền áp dụng các biện pháp, chế tài bao gồm nhưng không giới hạn nhắc nhở, tạm khóa Sản phẩm, giảm quảng cáo, giảm hiển thị Sản phẩm, giảm các chương trình hỗ trợ, khóa tài khoản hoặc chuyển sai phạm cho cơ quan nhà nước có thẩm quyền xử lý đồng thời yêu cầu Nhà Bán Hàng bồi thường cho Khách hàng thỏa đáng trên cơ sở thỏa thuận với Khách hàng.</div>
         <div class="work-bold" style="margin-bottom: 40px;">IV. QUY TRÌNH THANH TOÁN</div>
         <div class="work-text" style="margin-bottom: 40px;">Khách Hàng thực hiện thanh toán trực tuyến qua cổng thanh toán của Website dịch vụ thiết kế sửa chữa lắp đặt theo quy trình sau đây:</div>
         <div class="work-text" style="margin-bottom: 40px;"><span> Bước 1:</span> Khách Hàng tìm hiểu thông tin về Sản phẩm và đặt mua Sản phẩm.</div>
         <div class="work-text" style="margin-bottom: 40px;"><span>Bước 2:</span> Khách Hàng xác nhận đơn hàng và tiến hành thanh toán qua cổng thanh toán;</div>
         <div class="work-text" style="margin-bottom: 40px;"><span>Bước 3:</span> Nhà Bán Hàng xác nhận thông tin đơn hàng và thanh toán thành công của Khách Hàng.</div>
         <div class="work-text" style="margin-bottom: 40px;"><span>Bước 4</span>: Nhà Bán Hàng chuyển Sản phẩm.</div>
         <div class="work-text" style="margin-bottom: 40px;"><span>Bước 5:</span> Khách Hàng nhận Sản phẩm.</div>
         <div class="work-bold">V. ĐẢM BẢO AN TOÀN GIAO DỊCH</div>
         <div class="work-text" style="margin-bottom: 40px;">Website dịch vụ thiết kế sửa chữa lắp đặt tôn trọng và nghiêm túc thực hiện các quy định của pháp luật hiện hành về bảo vệ quyền lợi người tiêu dùng. Để đảm bảo các giao dịch được tiến hành thành công, hạn chế tối đa rủi ro có thể phát sinh, Website dịch vụ thiết kế sửa chữa lắp đặt đề nghị những cá nhân, tổ chức tham gia cung cấp hoặc sử dụng các dịch vụ trên Website phải cung cấp các thông tin chính xác, trung thực và chi tiết về sản phẩm của mình. Mọi hành vi gian lận trong kinh doanh đều bị lên án và phải hoàn toàn chịu trách nhiệm trước pháp luật.</div>
         <div class="work-text" style="margin-bottom: 40px;">Người đứng tên trên tài khoản đã đăng ký cũng như người dùng hoàn toàn chịu trách nhiệm về các thông tin đăng tải trong hồ sơ. Website dịch vụ thiết kế sửa chữa lắp đặt sẽ hỗ trợ nhanh nhất khi nhận được phản hồi, phàn nàn hay khiếu nại liên quan đến dịch vụ đã đăng trên Website bằng cách gỡ dịch vụ xuống, tạm thời không cho đăng ký mới, thông báo đến cộng đồng trên Website,...nếu nghiêm trọng có thể thông báo hủy tài khoản của bên cung cấp dịch vụ nếu Website dịch vụ thiết kế sửa chữa lắp đặt cảm thấy có hại cho uy tín của VNA hoặc quyền lợi của những Khách Hàng khác.</div>
         <div class="work-bold">VI. CHÍNH SÁCH BẢO VỆ THÔNG TIN CÁ NHÂN</div>
         <div class="work-bold">1. Mục đích thu thập Thông tin cá nhân:</div>
         <div class="work-text" style="margin-bottom: 40px;">Website dịch vụ thiết kế sửa chữa lắp đặt thu thập Thông tin cá nhân của thành viên bao gồm email, điện thoại, tên đăng nhập, địa chỉ Khách hàng. Đây là các thông tin mà Website dịch vụ thiết kế sửa chữa lắp đặt cần thành viên cung cấp bắt buộc khi đăng ký sử dụng dịch vụ và để Website dịch vụ thiết kế sửa chữa lắp đặt liên hệ xác nhận khi Khách hàng đăng ký sử dụng dịch vụ trên Website dịch vụ thiết kế sửa chữa lắp đặt nhằm đảm bảo quyền lợi cho cho người tiêu dùng.</div>
         <div class="work-text" style="margin-bottom: 40px;">Các Khách Hàng sẽ tự chịu trách nhiệm về bảo mật và lưu giữ mọi hoạt động sử dụng dịch vụ dưới tên đăng ký, mã xác nhận và hộp thư điện tử của mình. Ngoài ra, Khách Hàng có trách nhiệm thông báo kịp thời cho Website dịch vụ thiết kế sửa chữa lắp đặt về những hành vi sử dụng trái phép, lạm dụng, vi phạm bảo mật, lưu giữ tên đăng ký và mật khẩu của bên thứ ba để có biện pháp giải quyết phù hợp.</div>
         <div class="work-text" style="margin-bottom: 40px;">Mục đích thu thập Thông tin cá nhân:</div>
         <div class="work-text">Để cập nhật thông tin cho Khách Hàng chính sách của Nhà Bán Hàng dành cho Khách Hàng, các chính sách ưu đãi, chương trình khuyến mãi của Nhà Bán Hàng và Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text">Để tiến hành và quản lý việc đặt Sản Phẩm và giao nhận Sản Phẩm cho Khách Hàng.</div>
         <div class="work-text">Để đảm bảo sự an toàn khi Khách Hàng thực hiện giao dịch thanh toán trực tuyến.</div>
         <div class="work-text">Gửi các thông báo về các hoạt động trao đổi thông tin giữa Khách Hàng và Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text">Ngăn ngừa các hoạt động phá hủy tài khoản Khách Hàng hoặc các hoạt động giả mạo Khách Hàng để thực hiện giao dịch trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text">Tiếp nhận các đề nghị, góp ý của Khách Hàng, liên lạc và giải quyết các yêu cầu, khiếu nại của Khách Hàng.</div>
         <div class="work-text">Không sử dụng Thông tin cá nhân của Khách Hàng ngoài mục đích xác nhận và liên hệ có liên quan đến giao dịch tại Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;"> có trách nhiệm cung cấp thông tin cá nhân của Khách Hàng khi có yêu cầu từ cơ quan nhà nước có thẩm quyền hoặc theo quy định của pháp luật. Ngoài ra, không ai có quyền xâm phạm vào Thông tin cá nhân của Khách Hàng.</div>
         <div class="work-bold">2. Loại Thông tin cá nhân thu thập:</div>
         <div class="work-text">Thông tin cá nhân như họ và tên, giới tính, ngày sinh;</div>
         <div class="work-text">Thông tin liên lạc như số điện thoại, địa chỉ gửi thư, địa chỉ email, địa chỉ nhà và các thông tin khác liên quan đến yêu cầu đặc biệt của Khách hàng;</div>
         <div class="work-text">Thông tin về thanh toán nếu thanh toán bằng thẻ tín dụng hoặc thẻ ghi nợ như tên chủ thẻ, số thẻ, ngày hết hạn, mã xác thực;</div>
         <div class="work-text">Thông tin cá nhân được tự động tạo ra khi Khách Hàng sử dụng Website dịch vụ thiết kế sửa chữa lắp đặt như: thông tin IP, cookies, đăng nhập website.</div>
         <div class="work-text" style="margin-bottom: 40px;">Khách Hàng có quyền từ chối hoặc không cung cấp đầy đủ các thông tin được yêu cầu khi cần thiết. Trong trường hợp đó, Nhà Bán Hàng có thể sẽ không cung cấp cho Khách Hàng những Sản phẩm đầy đủ và chất lượng vì sự thiếu hụt thông tin.</div>
         <div class="work-bold">3. Phương thức thu thập thông tin: </div>
         <div class="work-text" style="margin-bottom: 40px;">Tùy vào Sản phẩm, Nhà Bán Hàng sẽ thu thập Thông tin cá nhân (tham khảo Điều 2 Chương VI) qua Website dịch vụ thiết kế sửa chữa lắp đặt nhằm giúp cho Nhà Bán Hàng cung cấp cho Khách Hàng những Sản phẩm đầy đủ và chất lượng theo yêu cầu của Khách Hàng.</div>
         <div class="work-bold">4. Thời gian lưu trữ thông tin </div>
         <div class="work-text" style="margin-bottom: 40px;">Nhà Bán Hàng lưu trữ Thông tin cá nhân của Khách Hàng trong suốt thời gian cung cấp Sản phẩm cho Khách Hàng hoặc cho đến khi hoàn thành mục đích thu thập (tham khảo Điều 1 Chương VI), hoặc khi Khách Hàng có yêu cầu hủy bỏ các Thông tin cá nhân đã cung cấp.</div>
         <div class="work-bold">5. Công bố Thông tin cá nhân thu thập: </div>
         <div class="work-text">Nhà Bán Hàng nỗ lực tốt nhất để đảm bảo rằng các nhân viên, cán bộ, đại lý, nhà tư vấn hoặc các bên thứ ba khác đề cập ở trên có liên quan đến việc thu thập, xử lý và công bố thông tin cá nhân sẽ kiểm soát và tuân thủ Chính sách bảo vệ thông tin cá nhân này.</div>
         <div class="work-text">Nhà Bán Hàng có thể công bố Thông tin cá nhân cho các cơ quan nhà nước có thẩm quyền, các cơ quan pháp luật và chính phủ vì lý do an ninh, hải quan, xuất nhập cảnh và các mục đích khác theo luật định đáp ứng yêu cầu của các cơ quan hoặc của pháp luật.</div>
         <div class="work-text">Nhà Bán Hàng có thể công bố Thông tin cá nhân cho bên thứ ba trong quá trình thực hiện đơn hàng của Khách Hàng theo sự đồng ý trước của Khách Hàng với mục đích cung cấp Sản phẩm tốt nhất.</div>
         <div class="work-text" style="margin-bottom: 40px;">Website dịch vụ thiết kế sửa chữa lắp đặt và Nhà Bán Hàng đảm bảo rằng, mọi Thông tin cá nhân do Khách Hàng cung cấp được các bên chia sẻ cho nhau hoặc cho bên thứ ba là hợp pháp và được sự đồng ý của Khách Hàng.</div>
         <div class="work-bold">6. Hủy Thông tin cá nhân: </div>
         <div class="work-text">Các Thông tin cá nhân thu thập sẽ bị hủy sau khi được lưu giữ trong một khoảng thời gian nhất định phù hợp với các chính sách nội bộ và vì các lý do khác để bảo vệ thông tin theo quy định của các luật có liên quan.</div>
         <div class="work-text" style="margin-bottom: 40px;">Các Thông tin cá nhân được in trên giấy sẽ được hủy bởi các phương tiện hủy giấy chuyên dụng hoặc bằng cách đốt bỏ, và các Thông tin cá nhân được lưu giữ bằng các thiết bị điện tử sẽ bị hủy bằng cách phương pháp điện tử phù hợp để bảm bảo chúng không thể phục hồi sau khi hủy.</div>
         <div class="work-bold">7. Quyền của Khách Hàng đối với các Thông tin cá nhân được thu thập: </div>
         <div class="work-text">Xem trước, sao chép, chỉnh sửa hoặc bổ sung Thông tin cá nhân.</div>
         <div class="work-text">Yêu cầu dừng thu thập Thông tin cá nhân.</div>
         <div class="work-text">Yêu cầu hủy Thông tin cá nhân đã thu thập.</div>
         <div class="work-text" style="margin-bottom: 40px;">Các quyền trên có thể thực hiện thông qua việc liên hệ trực tiếp với Nhà Bán Hàng thông qua đầu mối là Bộ phận CSKH.</div>
         <div class="work-bold">8. Thông tin cá nhân của trẻ em</div>
         <div class="work-text" style="margin-bottom: 40px;">Nhà Bán Hàng được thu thập và sử dụng các Thông tin cá nhân của trẻ em dưới 14 tuổi khi nhận được sự cho phép của người đại diện hợp pháp hoặc người bảo hộ của trẻ. Người đại diện hợp pháp/người bảo hộ của trẻ có thể yêu cầu được xem, chỉnh sửa Thông tin cá nhân của trẻ để xác nhận hoặc hủy.</div>
         <div class="work-bold">9. Các biện pháp kỹ thuật để bảo vệ Thông tin cá nhân:</div>
         <div class="work-text">Để đảm bảo sự an toàn của Thông tin cá nhân khỏi sự đánh cắp, rò rỉ, giả mạo hoặc thiệt hại, các nhân viên kỹ thuật của Nhà Bán Hàng sẽ tuân thủ các nguyên tắc về kỹ thuật, quản lý và thiết bị phần cứng như sau:</div>
         <div class="work-text" style="margin-bottom: 40px;">Các thông tin cá nhân quan trọng sẽ được lưu trữ và quản lý theo chế độ bảo mật với mật khẩu kèm truy cập hạn chế.</div>
         <div class="work-text">Các biện pháp để chống việc đánh cắp thông tin:</div>
         <div class="work-text">Nhà Bán Hàng triển khai các giải pháp ngăn chặn việc rò rỉ, thiệt hại Thông tin cá nhân của Khách Hàng từ tin tặc và virus máy tính;</div>
         <div class="work-text">Xây dựng bộ phận chuyên biệt dành riêng cho việc bảo mật Thông tin cá nhân, Nhà Bán Hàng đảm bảo rằng việc bảo vệ Thông tin cá nhân được kiểm soát và người phụ trách tuân thủ đúng các quy định được đề ra.</div>
         <div class="work-text">Giảm thiểu số lượng nhân viên trong việc quản lý Thông tin cá nhân.</div>
         <div class="work-text" style="margin-bottom: 40px;">Sử dụng hệ thống treo truy cập, kiểm soát truy cập trái phép từ bên ngoài.</div>
         <div class="work-bold" style="margin-bottom: 40px;">VII. QUẢN LÝ THÔNG TIN XẤU</div>
         <div class="work-bold" style="margin-bottom: 40px;">1. Quy định chung về đăng tải thông tin.</div>
         <div class="work-text" style="margin-bottom: 40px;">Nhà Bán Hàng và Khách Hàng cam kết không sử dụng các tiện ích, chức năng, dịch vụ và các chương trình của Website dịch vụ thiết kế sửa chữa lắp đặt vào (i) những mục đích bất hợp pháp, lừa đảo, đe dọa phát tán virus gây hư hại tới hệ thống, cấu hình, truyền tải thông tin của Vietnam Ailinres và đối tác của  vào Website dịch vụ thiết kế sửa chữa lắp đặt; (ii) mục đích đầu cơ, lũng đoạn thị trường tạo những đơn đặt hàng giả, kể cả phục vụ cho việc phán đoán nhu cầu thị trường.</div>
         <div class="work-text">Nhà Bán Hàng không được đăng bán, giới thiệu, quảng cáo bất kỳ Sản phẩm nào trên Website dịch vụ thiết kế sửa chữa lắp đặt hoặc Nhà bán Hàngthuộc các trường hợp sau đây:</div>
         <div class="work-text">Vi phạm pháp luật hoặc vi phạm thuần phong mỹ tục của Việt Nam;</div>
         <div class="work-text">Vi phạm các quyền sở hữu trí tuệ của bất kỳ bên thứ ba nào; vi phạm các cam kết bảo mật thông tin với bất kỳ bên thứ ba nào;</div>
         <div class="work-text">Gây ảnh hưởng tới hình ảnh, thương hiệu, gây mất uy tín của  và/hoặc Thương nhân và/hoặc Khách Hàng khác dưới mọi hình thức.</div>
         <div class="work-text" style="margin-bottom: 40px;">Nhà bán hàng và Khách Hàng không được cung cấp hoặc tác động để được cung cấp những thông tin:</div>
         <div class="work-text">Nhà bán hàng và Khách Hàng không được cung cấp hoặc tác động để được cung cấp những thông tin:</div>
         <div class="work-text">Không đúng sự thật, sai lệch.</div>
         <div class="work-text">Có tính chất phỉ báng hoặc gây mất uy tín của  và/hoặc Thương Nhân và/hoặc Khách Hàng khác, dưới mọi hình thức.</div>
         <div class="work-text" style="margin-bottom: 40px;">Gây ảnh hưởng, thiệt hại tới toàn bộ hoặc một phần các dịch vụ của Website dịch vụ thiết kế sửa chữa lắp đặt hoặc các nhà cung cấp dịch vụ cho Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-bold">2. Danh sách Sản phẩm cấm giao dịch trên Website dịch vụ thiết kế sửa chữa lắp đặt</div>
         <div class="work-italic" style="margin-bottom: 40px;">2.1. Danh sách Sản phẩm cấm giao dịch</div>
         <div class="work-text" style="margin-bottom: 40px;">-Rượu, đồ uống có cồn từ 15% trở lên.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Thuốc lá điếu, xì gà và các dạng thuốc lá thành phẩm khác.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Các loại pháo nổ, thuốc pháo nổ, chất nổ.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Các loại thuốc độc, thuốc ngủ, các loại độc dược; hóa chất độc; tiền chất.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Ma túy chất kích thích và các loại chất gây nghiện khác.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Thuốc lá điếu, xì gà và các dạng thuốc lá thành phẩm khác nhập lậu.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Thiết bị gây nhiễu thông tin di động tế bào.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Đèn trời.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Súng săn và đạn súng săn, vũ khí thể thao, công cụ hỗ trợ.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Vũ khí quân dụng, trang thiết bị, kĩ thuật, khí tài, phương tiện chuyên dùng quân sự, công an, quân trang.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Đồ chơi nguy hiểm, đồ chơi có hại tới giáo dục nhân cách và sức khỏe của trẻ em hoặc tới an ninh, trật tự, văn hóa xã hội (bao gồm cả các chương trình trò chơi điện tử).</div>
         <div class="work-text" style="margin-bottom: 40px;">-Sản phẩm khiêu dâm, dụng cụ kích dục, các dịch vụ môi giới mại dâm dưới mọi hình thức.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Sản phẩm có tính chất phân biệt chủng tộc, xúc phạm đến dân tộc hoặc quốc gia nào đó.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Di vật, cổ vật, bảo vật quốc gia thuộc di tích lịch sử văn hóa và danh lam thắng cảnh, thuộc sở hữu toàn dân, sở hữu của các tổ chức chính trị, tổ chức chính trị - xã hội.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Tài liệu bí mật quốc gia.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Đất đai, tài sản thuộc các khu vực/vùng địa lý công cộng.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Con người và/hoặc các bộ phận của cơ thể con người.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Thực vật, động vật hoang dã; bao gồm cả vật sống và các bộ phận của chúng đã được chế biến.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Thủy sản cấm khai thác, thủy sản có dư lượng chất độc hại vượt quá giới hạn cho phép, thủy sản có yếu tố độc tự nhiên gây nguy hiểm đến tính mạng con người.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Các loại thuốc chữa bệnh cho con người, các loại vắc xin, sinh phẩm y tế, mỹ phẩm, hóa chất và chế phẩm diệt côn trùng, diệt khuẩn trong lĩnh vực gia dụng và y tế chưa được sử dụng và bán tại Việt Nam; các loại thuốc không còn thời hạn đăng ký lưu hành; thuốc kê đơn; thuốc không kê đơn nhưng được cơ quan nhà nước có thẩm quyền khuyến cáo hạn chế sử dụng hoặc sử dụng có sự giám sát của bác sĩ.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Các loại trang thiết bị y tế chưa được phép sử dụng tại Việt Nam.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Các loại mỹ phẩm, thực phẩm chức năng chưa thực hiện thủ tục công bố với cơ quan nhà nước có thẩm quyền.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Các loại xe không có giấy tờ hay mất giấy tờ.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Danh sách email và/hoặc thông tin cá nhân của hàng loạt người.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Sản phẩm/phần mềm bất hợp pháp hoặc sử dụng chương trình bẻ khóa.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Các sản phẩm bất hợp pháp có nguồn gốc trộm, cướp.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Các hàng hóa cấm kinh doanh khác theo quy định của pháp luật.</div>
         <div class="work-italic">2.2. Hành vi cấm trong hoạt động giới thiệu, quảng cáo Sản phẩm trên Website dịch vụ thiết kế sửa chữa lắp đặt</div>
         <div class="work-text" style="margin-bottom: 40px;">Quảng cáo các hàng hóa, dịch vụ cấm quảng cáo theo quy định của pháp luật.</div>
         <div class="work-text" style="margin-bottom: 40px;">Quảng cáo thiếu thẩm mỹ, trái với truyền thống lịch sử, văn hóa, đạo đức, thuần phong mỹ tục Việt Nam.</div>
         <div class="work-text" style="margin-bottom: 40px;">Quảng cáo xúc phạm uy tín của tổ chức, danh dự, nhân phẩm của cá nhân.</div>
         <div class="work-text" style="margin-bottom: 40px;">Quảng cáo có hành động, lời nói, hình ảnh, âm thanh, chữ viết tạo cho trẻ em có suy nghĩ, lời nói, hành động trái với đạo đức, thuần phong mỹ tục; gây ảnh hưởng xấu đến sức khỏe, an toàn hoặc sự phát triển bình thường của trẻ em.</div>
         <div class="work-text" style="margin-bottom: 40px;">Quảng cáo có tính chất xâm phạm tự do tín ngưỡng, tôn giáo, định kiến về giới, về người khuyết tật.</div>
         <div class="work-text" style="margin-bottom: 40px;">Quảng cáo không đúng hoặc gây nhầm lẫn về khả năng kinh doanh, khả năng cung cấp sản phẩm, hàng hóa, dịch vụ của tổ chức, cá nhân kinh doanh sản phẩm, hàng hóa, dịch vụ; về số lượng, chất lượng, giá, công dụng, kiểu dáng, bao bì, nhãn hiệu, xuất xứ, chủng loại, phương thức phục vụ, thời hạn bảo hành của sản phẩm, hàng hoá, dịch vụ đã đăng ký hoặc đã được công bố.</div>
         <div class="work-text" style="margin-bottom: 40px;">Quảng cáo bằng việc sử dụng phương pháp so sánh trực tiếp về giá cả, chất lượng, hiệu quả sử dụng sản phẩm, hàng hóa, dịch vụ của mình với giá cả, chất lượng, hiệu quả sử dụng sản phẩm, hàng hóa, dịch vụ cùng loại của tổ chức, cá nhân khác.</div>
         <div class="work-text" style="margin-bottom: 40px;">Quảng cáo có nội dung cạnh tranh không lành mạnh theo quy định của pháp luật về cạnh tranh.</div>
         <div class="work-text" style="margin-bottom: 40px;">Quảng cáo vi phạm pháp luật về sở hữu trí tuệ.</div>
         <div class="work-text" style="margin-bottom: 40px;">Quảng cáo vi phạm pháp luật về quảng cáo.</div>
         <div class="work-bold" style="margin-bottom: 40px;">3. Cơ chế rà soát, kiểm soát thông tin đăng tải trên Website dịch vụ thiết kế sửa chữa lắp đặt </div>
         <div class="work-text" style="margin-bottom: 40px;">3.1. Đối với việc đăng tải thông tin Sản phẩm do Nhà Bán Hàng thực hiện, bài đăng sẽ được hiển thị ngay lập tức trên gian hàng của Nhà Bán Hàng. Website dịch vụ thiết kế sửa chữa lắp đặt sẽ thực hiện kiểm duyệt nội dung thông tin trong vòng 24h. Những thông tin về Sản phẩm vi phạm pháp luật, vi phạm quy định của Quy chế, nhưng thông tin không được đăng đúng chuyên mục về Sản phẩm sẽ bị loại bỏ khỏi Website dịch vụ thiết kế sửa chữa lắp đặt. Website dịch vụ thiết kế sửa chữa lắp đặt sẽ ẩn thông tin Sản phẩm và gửi cảnh báo đến Nhà Bán Hàng qua email để yêu cầu chỉnh sửa.</div>
         <div class="work-text" style="margin-bottom: 40px;">3.2. Đối với việc kiểm duyệt thông tin Sản phẩm do Nhà Bán Hàng và/hoặc Khách Hàng phản ánh, Website dịch vụ thiết kế sửa chữa lắp đặt sẽ tiến hành liên hệ trực tiếp đến tổ chức, cá nhân phản ánh để xác thực thông tin.</div>
         <div class="work-text" style="margin-bottom: 40px;">3.3. Những thông tin về Sản phẩm vi phạm pháp luật, vi phạm quy định của Quy chế sẽ bị loại bỏ khỏi Website dịch vụ thiết kế sửa chữa lắp đặt. Website dịch vụ thiết kế sửa chữa lắp đặt sẽ ngay lập tức ẩn các thông tin Sản phẩm này và gửi cảnh báo đến Nhà Bán Hàng qua email.</div>
         <div class="work-text" style="margin-bottom: 40px;">3.4. Những thông tin về Sản phẩm không được đăng phù hợp với các chuyên mục Sản phẩm đăng tin theo quy định sẽ bị xóa hoặc được Website dịch vụ thiết kế sửa chữa lắp đặt chuyển sang chuyên mục Sản phẩm khác được cho là hợp lý.</div>
         <div class="work-text" style="margin-bottom: 40px;">3.5. Website dịch vụ thiết kế sửa chữa lắp đặt có toàn quyền quyết định việc lưu giữ hoặc loại bỏ thông tin Sản phẩm được đăng trên Website dịch vụ thiết kế sửa chữa lắp đặt mà không cần báo trước.</div>
         <div class="work-text" style="margin-bottom: 40px;">3.6. Trong trường hợp vi phạm pháp luật, Nhà Bán Hàng và Khách Hàng phải chịu hoàn toàn trách nhiệm về các hành vi của mình trước pháp luật.</div>
         <div class="work-bold" style="margin-bottom: 40px;">VIII. TRÁCH NHIỆM TRONG TRƯỜNG HỢP PHÁT SINH LỖI KỸ THUẬT</div>
         <div class="work-text" style="margin-bottom: 40px;">1. Khi thực hiện các giao dịch trên Website dịch vụ thiết kế sửa chữa lắp đặt, Khách hàng và Nhà Bán Hàng phải tuân thủ các quy trình đã được hướng dẫn.</div>
         <div class="work-text" style="margin-bottom: 40px;">2. Ban quản lý Website dịch vụ thiết kế sửa chữa lắp đặt cam kết cung cấp chất lượng dịch vụ thương mại điện tử tốt nhất cho Khách Hàng và Nhà Bán Hàng và đảm bảo tuân thủ quy định của pháp luật. Trường hợp phát sinh lỗi kỹ thuật, lỗi phần mềm hoặc các lỗi khách quan khác dẫn đến việc Khách Hàng và Nhà Bán Hàng không thể tham gia giao dịch, Khách Hàng/nhà Bán Hàng thông báo cho Ban quản lý Website dịch vụ thiết kế sửa chữa lắp đặt qua địa chỉ email: helpdesk.C&D@vietnamairlines.com. Chúng tôi sẽ khắc phục lỗi trong thời gian sớm nhất, tạo điều kiện cho Khách Hàng và Nhà Bán Hàng tham gia Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">3. Tuy nhiên, Ban quản lý Website dịch vụ thiết kế sửa chữa lắp đặt sẽ không chịu trách nhiệm đối với các thiệt hại, tổn thất của Khách Hàng và Nhà Bán Hàng trong trường hợp (i) thông báo của Khách Hàng và Nhà Bán Hàng không đến được Ban quản lý Website dịch vụ thiết kế sửa chữa lắp đặt, (ii) phát sinh từ lỗi kỹ thuật, lỗi đường truyền, lỗi phần mềm hoặc các lỗi khách quan khác không do Ban quản lý Website dịch vụ thiết kế sửa chữa lắp đặt gây ra.</div>
         <div class="work-bold" style="margin-bottom: 40px;">IX. QUYỀN VÀ TRÁCH NHIỆM CỦA BAN QUẢN LÝ Website dịch vụ thiết kế sửa chữa lắp đặt</div>
         <div class="work-text" style="margin-bottom: 40px;">1. Quyền của Ban quản lý Website dịch vụ thiết kế sửa chữa lắp đặt ():</div>
         <div class="work-text" style="margin-bottom: 40px;">1.1. Ban quản lý Website dịch vụ thiết kế sửa chữa lắp đặt có quyền kiểm tra thông tin Nhà Bán Hàng đăng tải, đặc biệt là các thông tin giới thiệu, quảng cáo về Sản phẩm.</div>
         <div class="work-text" style="margin-bottom: 40px;">1.2. Từ chối, tạm ngừng hoặc chấm dứt cung cấp dịch vụ cho Nhà Bán Hàng trong các trường hợp có cơ sở chứng minh cá nhân, tổ chức cung cấp thông tin, đăng tải thông tin trên Website dịch vụ thiết kế sửa chữa lắp đặt không chính xác, không đầy đủ, vi phạm pháp luật, trái với đạo đức và thuần phong mỹ tục Việt Nam.</div>
         <div class="work-text" style="margin-bottom: 40px;">1.3. Từ chối, cung cấp một hoặc tất cả dịch vụ trên Website dịch vụ thiết kế sửa chữa lắp đặt trong trường hợp các Nhà Bán Hàng, Khách Hàng vi phạm Quy chế hoặc có những hành vi ảnh hưởng đến hình ảnh, cơ sở dữ liệu, uy tín kinh doanh của Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">1.4. Website dịch vụ thiết kế sửa chữa lắp đặt giữ bản quyền sử dụng các dịch vụ và các nội dung trên Website dịch vụ thiết kế sửa chữa lắp đặt theo luật bản quyền quốc tế và các quy định pháp luật về bảo hộ sở hữu trí tuệ tại Việt Nam. Nghiêm cấm mọi hành vi sao chép, sử dụng và phổ biến bất hợp pháp các quyền sở hữu trên.</div>
         <div class="work-text" style="margin-bottom: 40px;">1.5. Ban quản lý Website dịch vụ thiết kế sửa chữa lắp đặt có quyền được thay đổi bảng giá, biểu giá dịch vụ và phương thức thanh toán trong thời gian cung cấp dịch vụ TMĐT cho Nhà Bán Hàng và Khách Hàng theo nhu cầu và điều kiện khả năng của Website dịch vụ thiết kế sửa chữa lắp đặt và sẽ thông báo cho Nhà Bán Hàng và Khách Hàng trong thời hạn là 01 (một) tuần trước khi thực hiện các thay đổi.</div>
         <div class="work-text" style="margin-bottom: 40px;">1.6. Ban quản lý Website dịch vụ thiết kế sửa chữa lắp đặt có quyền kiểm duyệt, giám soát thông tin đăng tải trên Website dịch vụ thiết kế sửa chữa lắp đặt và áp dụng các biện pháp cần thiết để đảm bảo tuân thủ quy định pháp luật và Quy chế. Ngoài ra,  có quyền chấm dứt Hợp Đồng nếu Nhà Bán Hàng vi phạm.</div>
         <div class="work-text" style="margin-bottom: 40px;">1.7. Website dịch vụ thiết kế sửa chữa lắp đặt có quyền:</div>
         <div class="work-text" style="margin-bottom: 40px;">Chấm dứt Hợp đồng với Nhà Bán Hàng theo quy định của Hợp đồng.</div>
         <div class="work-text" style="margin-bottom: 40px;">Chấm dứt, tạm đình chỉ tài khoản hoặc quyền sử dụng dịch vụ của Khách Hàng trong trường hợp Khách Hàng có hành vi vi phạm pháp luật và vi phạm Quy chế, tùy vào mức độ nghiêm trọng của hành vi vi phạm. Trong trường hợp chấm dứt tài khoản hoặc quyền sử dụng dịch vụ, tất cả các chứng nhận, các quyền của Khách Hàng được cấp trên Website dịch vụ thiết kế sửa chữa lắp đặt sẽ mặc nhiên hết giá trị.</div>
         <div class="work-bold" style="margin-bottom: 40px;">2. Trách nhiệm của Ban quản lý Website dịch vụ thiết kế sửa chữa lắp đặt ()</div>
         <div class="work-text" style="margin-bottom: 40px;">2.1. Đăng ký thiết lập Website dịch vụ thiết kế sửa chữa lắp đặt với cơ quan nhà nước có thẩm quyền theo quy định của pháp luât và đảm bảo hoạt động của Website dịch vụ thiết kế sửa chữa lắp đặt tuân thủ các quy định pháp luật hiện hành.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.2. Xây dựng, thực hiện cơ chế kiểm tra, giám sát để đảm bảo việc cung cấp thông tin của Website dịch vụ thiết kế sửa chữa lắp đặt được thực hiện chính xác đầy đủ theo quy định tại Điều 36 Nghị định 52/2013/NĐ-CP.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.3. Hỗ trợ cơ quan nhà nước có thẩm quyền trong việc điều tra các hành vi kinh doanh vi phạm pháp luật, cung cấp thông tin đăng ký, lịch sử giao dịch và các tài liệu khác về đối tượng có hành vi vi phạm pháp luật trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.4. Website dịch vụ thiết kế sửa chữa lắp đặt chịu trách nhiệm xây dựng, cập nhật các kiến thức, thông tin về nghiệp vụ ngoại thương, thương mại điện tử, hệ thống văn bản pháp luật thương mại trong nước và quốc tế và các tin tức, thông tin có liên quan đến hoạt động của Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.5. Website dịch vụ thiết kế sửa chữa lắp đặt sẽ tiến hành các hoạt động xúc tiến, quảng bá Website dịch vụ thiết kế sửa chữa lắp đặt ra thị trường nước ngoài trong phạm vi và điều kiện cho phép, góp phần mở rộng, kết nối đáp ứng các nhu cầu tìm kiếm bạn hàng và phát triển thị trường nước ngoài của các Nhà Bán Hàng tham gia Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.6. Website dịch vụ thiết kế sửa chữa lắp đặt sẽ cố gắng đến mức cao nhất trong phạm vi và điều kiện cho phép để duy trì hoạt động bình thường của Website dịch vụ thiết kế sửa chữa lắp đặt và khắc phục các sự cố như sự cố kỹ thuật về máy móc, lỗi phần mềm, lỗi hệ thống đường truyền internet, sự cố về nhân sự hoặc các sự kiện bất khả kháng bao gồm nhưng không giới hạn như các biến động xã hội, thiên tai, dịch bệnh, mất điện, các quyết định của cơ quan nhà nước có thẩm quyền. Tuy nhiên, trong trường hợp xảy ra các thiệt hại cho Nhà Bán Hàng và Khách Hàng phát sinh từ những sự kiện bất khả kháng nằm ngoài kiểm soát của Website dịch vụ thiết kế sửa chữa lắp đặt, Website dịch vụ thiết kế sửa chữa lắp đặt sẽ không phải chịu các trách nhiệm liên đới.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.7. Ngăn chặn và loại bỏ khỏi Website những thông tin của Sản phẩm thuộc danh mục hàng hóa, dịch vụ cấm kinh doanh, thông tin quảng cáo Sản phẩm vi phạm theo quy định của pháp luật và cấm giao dịch trên Website dịch vụ thiết kế sửa chữa lắp đặt (tham khảo Điều 2 Chương VII)</div>
         <div class="work-text" style="margin-bottom: 40px;">2.8. Loại bỏ khỏi Website dịch vụ thiết kế sửa chữa lắp đặt những thông tin bán hàng giả, hàng nhái, hàng nhập lậu, hàng vi phạm quyền sở hữu trí tuệ và các hàng hóa, dịch vụ vi phạm pháp luật khác khi phát hiện hoặc nhận được phản ánh có căn cứ xác thực về những thông tin này.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.9. Yêu cầu Nhà Bán Hàng cung cấp các thông tin khi đăng ký sử dụng dịch vụ TMĐT của Website dịch vụ thiết kế sửa chữa lắp đặt:</div>
         <div class="work-text" style="margin-bottom: 40px;">- Tên và địa chỉ trụ sở của tổ chức hoặc tên và địa chỉ thường trú của cá nhân.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Số điện thoại liên hệ hoặc một phương thức liên hệ trực tuyến khác</div>
         <div class="work-text" style="margin-bottom: 40px;">- Số, ngày cấp và nơi cấp giấy chứng nhận đăng ký kinh doanh của Nhà Bán Hàng hoặc số, ngày cấp và đơn vị cấp quyết định thành lập của tổ chức hoặc mã số thuế cá nhân, số CMND của cá nhân</div>
         <div class="work-text" style="margin-bottom: 40px;">- Giấy chứng nhận đủ điều kiện kinh doanh đối với hàng hóa, dịch vụ đó (trong trường hợp pháp luật quy định phải có Giấy chứng nhận đủ điều kiện kinh doanh).</div>
         <div class="work-text" style="margin-bottom: 40px;">2.10. Website dịch vụ thiết kế sửa chữa lắp đặt có quyền đơn phương chấm dứt Hợp đồng với Nhà Bán Hàng nếu Nhà Bán Hàng sử dụng và cung cấp các giấy tờ giả mạo hoặc có hoạt động kinh doanh bất hợp pháp theo quy định tại Hợp đồng. Nhà Bán Hàng sẽ chịu hoàn toàn trách nhiệm trước pháp luật.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.11. Xây dựng Quy chế hoạt động của Website dịch vụ thiết kế sửa chữa lắp đặt và và công bố công khai trên Website dịch vụ thiết kế sửa chữa lắp đặt, theo dõi và bảo đảm việc thực hiện Quy chế này trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.12. Lưu trữ thông tin đăng ký của Nhà Bán Hàng, các tổ chức, cá nhân tham gia Website dịch vụ thiết kế sửa chữa lắp đặt và thường xuyên cập nhật những thông tin thay đổi, bổ sung có liên quan.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.13. Áp dụng các biện pháp cần thiết để đảm bảo an toàn thông tin liên quan đến bí mật kinh doanh của Nhà Bán Hàng và Thông tin cá nhân của Khách Hàng. Không được tiết lộ, chuyển nhượng, cho thuê hoặc bán các thông tin này khi chưa được sự đồng ý của các bên liên quan, trừ trường hợp pháp luật có quy định khác. Tuân thủ Chính sách bảo vệ Thông tin cá nhân được định tại Quy chế này.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.14. Thiết lập cơ chế cung cấp thông tin và giao kết hợp đồng trên Website dịch vụ thiết kế sửa chữa lắp đặt cho phép Nhà Bán Hàng, Khách Hàng và các tổ chức, cá nhân tham gia hoạt động trên Website dịch vụ thiết kế sửa chữa lắp đặt thực hiện được quy trình giao kết hợp đồng trực tuyến.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.15. Triển khai và hợp tác với các đối tác trong việc xây dựng hệ thống các dịch vụ, các công cụ tiện ích phục vụ cho việc giao dịch của các Nhà Bán Hàng và Khách Hàng tham gia giao dịch trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.16. Có biện pháp xử lý kịp thời khi phát hiện hoặc nhận được phản ánh về hành vi kinh doanh vi phạm pháp luật trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.17. Công bố công khai cơ chế giải quyết các tranh chấp phát sinh trong quá trình giao dịch trên Website dịch vụ thiết kế sửa chữa lắp đặt. Website dịch vụ thiết kế sửa chữa lắp đặt có trách nhiệm đứng ra làm trung gian trong việc hòa giải nếu xảy ra tranh chấp giữa Khách hàng và Nhà Bán Hàng và thực hiện giải quyết các khiếu nại của Khách Hàng theo quy trình giải quyết khiếu nại tại Quy chế này (tham khảo Điều 6), đảm bảo quyền và lợi ích hợp pháp của Khách Hàng.</div>
         <div class="work-text" style="margin-bottom: 40px;">2.18. Tuân thủ các quy định pháp luật có liên quan về hoạt động cung cấp dịch vụ sàn giao dịch TMĐT, đặt hàng trực tuyến, thanh toán trực tuyến, khuyến mại trực tuyến.</div>
         <div class="work-bold" style="margin-bottom: 40px;">X. QUYỀN VÀ TRÁCH NHIỆM CỦA CÁC BÊN THAM GIA Website dịch vụ thiết kế sửa chữa lắp đặt</div>
         <div class="work-bold" style="margin-bottom: 40px;">1. Quyền và trách nhiệm của Nhà Bán Hàng .</div>
         <div class="work-text" style="margin-bottom: 40px;">- Sau khi ký Hợp đồng, Nhà Bán Hàng được tạo một gian hàng riêng để giới thiệu Sản phẩm và tiến hành kinh doanh và quảng bá doanh nghiệp trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Có quyền quyết định về hình ảnh, thông tin của mình được đăng tải trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Có quyền được góp ý về nội dung liên quan đến đăng tải trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Nhà Bán Hàng sẽ được hỗ trợ đào tạo những kỹ năng cần thiết để quản trị gian hàng, đăng Sản phẩm trên Website dịch vụ thiết kế sửa chữa lắp đặt thông qua tổng đài hỗ trợ hoặc email đến bộ phận hỗ trợ của Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Nhà Bán Hàng sẽ được hưởng các chính sách ưu đãi khác của Website dịch vụ thiết kế sửa chữa lắp đặt hoặc của các đối tác thứ ba của  trên Website dịch vụ thiết kế sửa chữa lắp đặt. Các chính sách ưu đãi này sẽ được đăng tải, cập nhật trên Website dịch vụ thiết kế sửa chữa lắp đặt hoặc được gửi trực tiếp đến Nhà Bán Hàng.</div>
         <div class="work-bold" style="margin-bottom: 40px;">1.2. Trách nhiệm Nhà Bán Hàng:</div>
         <div class="work-text" style="margin-bottom: 40px;">- Cung cấp đầy đủ và chính xác các thông tin của mình cho Website dịch vụ thiết kế sửa chữa lắp đặt khi đăng ký sử dụng dịch vụ TMĐT của Website dịch vụ thiết kế sửa chữa lắp đặt (tham khảo Khoản 2.9 Điều 2 Chương IX).</div>
         <div class="work-text" style="margin-bottom: 40px;">- Chịu toàn bộ trách nhiệm trước pháp luật về các hồ sơ mà Nhà Bán Hàng cung cấp cho Sàn giao dịch TMĐT VNA để đảm bảo tính hợp pháp của hoạt động bán hàng và Sản phẩm của Nhà Bán Hàng trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Đảm bảo tính chính xác, trung thực, đầy đủ của thông tin về Sản phẩm được đăng bán trên Website dịch vụ thiết kế sửa chữa lắp đặt. Việc mô tả Sản phẩm phải rõ ràng, chính xác tránh gây hiểu lầm đến Khách Hàng; đối với các Sản phẩm thuộc danh mục hàng hóa kinh doanh có điều kiện theo quy định của pháp luật, Nhà bán hàng phải đính kèm mô tả Sản phẩm các giấy phép, giấy chứng nhận như: Giấy chứng nhận đủ điều kiện kinh doanh, Giấy chứng nhận tiêu chuẩn Sản phẩm, Giấy công bố chất lượng, Giấy chứng nhận ATTP, Giấy xác nhận nội dung quảng cáo,… Nhà Bán Hàng cam kết các thông tin, giấy tờ cung cấp là chính xác và hợp pháp. Các giấy tờ phải là bản gốc hoặc bản sao y có công chứng, chứng thực.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Trong trường hợp Nhà Bán Hàng là chủ sở hữu một Sản phẩm có nhãn hiệu hoặc là đại lý ủy quyền thì Nhà Bán Hàng có trách nhiệm cung cấp một (01) bản sao có công chứng Giấy chứng nhận đăng ký nhãn hiệu hoặc Giấy ủy quyền của chủ sở hữu Sản phẩm hoặc nhãn hàng đó.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Đảm bảo về chất lượng, nguồn gốc, xuất xứ đối với Sản phẩm và phải chịu hoàn toàn trách nhiệm trước pháp luật và Khách Hàng.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Tuân thủ quy định của pháp luật về thanh toán, quảng cáo, khuyến mại, sở hữu trí tuệ, bảo vệ quyền lợi người tiêu dùng và các quy định của pháp luật có liên quan khác khi bán Sản phẩm hoặc cung ứng dịch vụ trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Thực hiện đầy đủ nghĩa vụ thuế theo quy định của pháp luật.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Đối với việc xử lý đơn hàng, đóng gói và giao Sản phẩm, Nhà Bán Hàng cam kết đảm bảo giao đúng, đủ hàng hóa, theo đơn hàng của Khách Hàng. Cam kết thực hiện đúng các quy trình về xử lý đơn hàng, chuẩn bị đóng gói, vận chuyển Sản phẩm.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Cung cấp đầy đủ, rõ ràng cho Khách Hàng và cập nhật trên Website dịch vụ thiết kế sửa chữa lắp đặt chính sách đổi - trả Sản phẩm, chính sách hoàn tiền, chính sách bảo hành Sản phẩm</div>
         <div class="work-text" style="margin-bottom: 40px;">- Chịu trách nhiệm hoặc phối hợp tích cực với Website dịch vụ thiết kế sửa chữa lắp đặt giải quyết những khiếu nại của Khách Hàng, những tranh chấp giữa Khách Hàng với Nhà Bán Hàng liên quan đến Sản phẩm và các giao dịch qua Website dịch vụ thiết kế sửa chữa lắp đặt theo quy định tại Hợp đồng và theo quy định tại Quy chế này.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Nhà Bán Hàng có nghĩa vụ bồi thường thiệt hại cho Khách Hàng theo thỏa thuận với Khách Hàng khi lỗi được xác định thuộc về Nhà Bán Hàng.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Bồi thường thiệt hại cho  đối với những thiệt hại, tổn thất, chi phí mà  phải chịu do Nhà Bán Hàng vi phạm các quy định của pháp luật hoặc vi phạm các quy định của Quy chế này.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Không sử dụng dịch vụ của Website dịch vụ thiết kế sửa chữa lắp đặt vào những mục đích bất hợp pháp, không hợp lý, lừa đảo, đe doạ, thăm dò thông tin bất hợp pháp, phá hoại, tạo ra và phát tán virus gây hư hại tới hệ thống, cấu hình, truyền tải thông tin của Website dịch vụ thiết kế sửa chữa lắp đặt hay sử dụng dịch vụ của mình vào mục đích đầu cơ, lũng đoạn thị trường tạo những đơn đặt hàng, chào hàng giả, kể cả phục vụ cho việc phán đoán nhu cầu thị trường. Trong trường hợp vi phạm, Nhà Bán Hàng phải chịu trách nhiệm về các hành vi của mình trước pháp luật.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Không được thay đổi, chỉnh sửa, gán ghép, copy, truyền bá, phân phối, cung cấp và tạo những công cụ tương tự của dịch vụ do Website dịch vụ thiết kế sửa chữa lắp đặt cung cấp cho một bên thứ ba nếu không được sự đồng ý của Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Không được hành động gây mất uy tín của Website dịch vụ thiết kế sửa chữa lắp đặt, không cạnh tranh tiêu cực dưới mọi hình thức bao gồm nhưng không giới hạn gian lận điểm uy tín, điểm hoạt động, gian lận lượt mua, gây mất đoàn kết giữa các Nhà Bán Hàng hoặc phá hoại hoạt động kinh doanh của các Nhà Bán Hàng khác trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Cung cấp thông tin về tình hình kinh doanh của mình khi có yêu cầu của cơ quan nhà nước có thẩm quyền để phục vụ hoạt động thống kê thương mại điện tử.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Yêu cầu Nhà Bán Hàng chấm dứt ngay hành vi vi phạm</div>
         <div class="work-text" style="margin-bottom: 40px;">- Không xác nhận, từ chối hoặc hủy các đơn hàng phát sinh từ hành vi vi phạm nêu trên</div>
         <div class="work-text" style="margin-bottom: 40px;">- Khấu trừ mọi chi phí mà Website dịch vụ thiết kế sửa chữa lắp đặt đã bỏ ra (nếu có) để triển khai chương trình khuyến mại vào các khoản phải thanh toán cho Nhà Bán Hàng theo Hợp đồng.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Tuân thủ các nghĩa vụ, cam kết khác của Nhà Bán Hàng được quy định tại Quy chế này.</div>
         <div class="work-bold" style="margin-bottom: 40px;">2. Quyền và trách nhiệm của Khách hàng</div>
         <div class="work-bold" style="margin-bottom: 40px;">2.1. Quyền của Khách hàng</div>
         <div class="work-text" style="margin-bottom: 40px;">- Được tạo tài khoản và tham gia giao dịch tại Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Được cấp tên đăng ký và mã xác nhận để sử dụng tài khoản dành cho Khách Hàng và quản lý đơn hàng trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Được Website dịch vụ thiết kế sửa chữa lắp đặt cung cấp, hỗ trợ thông tin, giải đáp thắc mắc, khiếu nại khi có nhu cầu qua Bộ phận CSKH của Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Khách Hàng được tìm hiểu, chọn lựa đa dạng các Sản phẩm từ nhiều gian hàng trên Website dịch vụ thiết kế sửa chữa lắp đặt, được so sánh mức giá và chất lượng Sản phẩm trước khi quyết định đặt mua.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Khách Hàng có quyền yêu cầu cơ quan nhà nước có thẩm quyền bảo vệ khi quyền và lợi ích hợp pháp bị xâm phạm.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Khách Hàng được hưởng các ưu đãi từ Website dịch vụ thiết kế sửa chữa lắp đặt và Nhà Bán Hàng nếu tham gia đăng kí thành viên và đạt danh hiệu thành viên mua hàng thường xuyên trên Website dịch vụ thiết kế sửa chữa lắp đặt.</div>
         <div class="work-bold" style="margin-bottom: 40px;">2.2. Trách nhiệm của Khách hàng</div>
         <div class="work-text" style="margin-bottom: 40px;">-Khách Hàng trách nhiệm tuân thủ các quy định, quy trình trong Quy chế này. Khách Hàng phải đọc Quy chế này và các quy định có liên quan công bố trên Website dịch vụ thiết kế sửa chữa lắp đặt trước khi đặt mua Sản phẩm. Khi Khách Hàng thao tác xác nhận mua Sản phẩm, Website dịch vụ thiết kế sửa chữa lắp đặt mặc định Khách Hàng đã đọc Quy chế này và không chịu trách nhiệm với bất kì các khiếu nại, tranh chấp, thiệt hại phát sinh từ việc Khách Hàng không tuân thủ Quy chế.</div>
         <div class="work-text" style="margin-bottom: 40px;">-Thông báo kịp thời cho Website dịch vụ thiết kế sửa chữa lắp đặt khi phát hiện có hành vi vi phạm Quy chế, quy định của pháp luật của các cá nhân, tổ chức khác khi tham gia giao dịch tại Website dịch vụ thiết kế sửa chữa lắp đặt và phối hợp với Website dịch vụ thiết kế sửa chữa lắp đặt để giải quyết.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Cam kết và đồng ý không sử dụng dịch vụ của Website dịch vụ thiết kế sửa chữa lắp đặt vào các mục đích bất hợp pháp, lừa đảo, đe dọa hoặc các hành vi khác vi phạm quy định của pháp luật. Khách Hàng chịu trách nhiệm hoàn toàn trước pháp luật về những hành vi vi phạm pháp luật này.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Không có những hành vi gây mất uy tín hoặc ảnh hưởng xấu đến hoạt động kinh doanh của Website dịch vụ thiết kế sửa chữa lắp đặt và của các Nhà Bán Hàng dưới mọi hình thức.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Khách Hàng phải chịu trách nhiệm và đảm bảo tính trung thực trong việc phản hồi, khiếu nại về Sản phẩm với Website dịch vụ thiết kế sửa chữa lắp đặt và Nhà Bán Hàng.</div>
         <div class="work-text" style="margin-bottom: 40px;">- Sử dụng dịch vụ một cách văn minh trên Website dịch vụ thiết kế sửa chữa lắp đặt, không được có những thông tin xuyên tạc, thiếu chính xác gây bất lợi cho Website dịch vụ thiết kế sửa chữa lắp đặt và .</div>
         <div class="work-bold" style="margin-bottom: 40px;">XI. ĐIỀU KHOẢN ÁP DỤNG</div>
         <div class="work-text" style="margin-bottom: 40px;">1.Quy chế hoạt động của Website dịch vụ thiết kế sửa chữa lắp đặt chính thức có hiệu lực thi hành kể từ ngày ký Quyết định ban hành kèm theo Quy chế này.</div>
         <div class="work-text" style="margin-bottom: 40px;">2. Mọi Nhà Bán Hàng và Khách Hàng khi sử dụng Website dịch vụ thiết kế sửa chữa lắp đặt để thực hiện hoạt động mua bán trực tuyến thì đồng nghĩa với việc đã chấp thuận tuân thủ Quy chế này.</div>
         <div class="work-text" style="margin-bottom: 50px;">3. Website dịch vụ thiết kế sửa chữa lắp đặt có quyền thay đổi, chỉnh sửa Quy chế này bằng cách thông báo cho Nhà Bán Hàng và Khách Hàng thông qua email ít nhất 05 (năm) ngày trước khi áp dụng những thay đổi đó. Sau 5 (năm) ngày thông báo, Quy chế được sửa đổi, bổ sung hoặc thay thế chính thức có hiệu lực. Việc Nhà Bán Hàng và Khách Hàng tiếp tục sử dụng dịch vụ của Website dịch vụ thiết kế sửa chữa lắp đặt sau khi Quy chế sửa đổi được công bố và thực thi đồng nghĩa với việc Nhà Bán Hàng và Khách Hàng đã chấp nhận Quy chế sửa đổi này.</div>
         <div class="work-text">Địa chỉ liên lạc chính thức của Website dịch vụ thiết kế sửa chữa lắp đặt: </div>
         <div class="work-text">Website dịch vụ thiết kế sửa chữa lắp đặt: http://C&D.smiletech.vn/</div>
         <div class="work-text">Vận hành bởi Tổng công ty Hàng không Việt Nam - CTCP và Viện quản trị Logistics Toàn cầu.</div>
         <div class="work-text">Địa chỉ: http://C&D.smiletech.vn/</div>
         <div class="work-text">Hotline: 1900 1033</div>
         <div class="work-text" style="margin-bottom: 80px;">Email: C&D.smiletech.vn</div>
      </div>
   </div>
</div>
`;

const InfoduceWeb = () => {
  return parse(introduce);
  // return (
  // )
};

export default InfoduceWeb;
